### ISSUE TITLE
书中讲到动态改变布局的问题?

### ISSUE THREAD

**Issue by zzz40500** [xuyisheng/AndroidHeroes#1]
适配器 也就是这个FocusListViewAdapter, 但是没有实现 ViewHodler 实现.不能为了实现动态改变而放弃ViewHodler模式.既然都是用 notifyDataSetChanged() 方法,为啥不用 viewtype 来实现这个效果?

**Comment by xuyisheng** [comment]
只是单纯的为了讲解知识点~ 所以代码并不是最优的
