### ISSUE TITLE
『勘误』-第五章Scroll分析

### ISSUE THREAD

**Issue by icodeu** [xuyisheng/AndroidHeroes#3]
P90 图5.3，这是我见过讲的最明白的获取坐标系距离的方法 :+1: ；但是 `getBottom()` 是否标识有误呢？对应该图来讲，我觉得应该是 `ViewGroup的顶部 到 View的底部 的距离`，而不是图中最外层的顶部。

望有时间查看，或许是我自己理解的有误

**Comment by xuyisheng** [comment]
是标注有错哈 已经收录勘误了 http://blog.csdn.net/eclipsexys/article/details/48297991
